export const featuredWorks = [
  {
    id: 'azure-empress',
    title: 'Azure Empress',
    category: 'Illustration',
    tagColor: 'pink',
    description: 'A personal piece inspired by eastern fantasy and moonlit nights. Exploring the balance between tranquility and power through flowing silks and celestial motifs.',
    note: 'Personal favorite — took three attempts to get the lighting right.',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    accentColor: '#A8D4D8',
    emoji: '🌙',
  },
  {
    id: 'eclipse-of-eternity',
    title: 'Eclipse of Eternity',
    category: 'VTuber Key Visual',
    tagColor: 'lavender',
    description: 'Key visual for a VTuber character with a dark fantasy theme. The brief asked for "someone who walks between worlds" — this is her.',
    note: 'Commission. Client wanted sakura + darkness. I loved this challenge.',
    gradient: 'linear-gradient(135deg, #2d1b33 0%, #1a0a2e 50%, #3d0a0a 100%)',
    accentColor: '#E8A4B0',
    emoji: '✦',
  },
  {
    id: 'forgotten-paths',
    title: 'Forgotten Paths',
    category: 'Background Illustration',
    tagColor: 'cyan',
    description: 'Background artwork for a fantasy world-building project. Soft atmospheric architecture, ancient and serene, kissed by morning mist.',
    note: 'Environment work is meditative — I lose hours in these.',
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #2a3a4a 50%, #3a4a5a 100%)',
    accentColor: '#C4B8D4',
    emoji: '🏯',
  },
  {
    id: 'sweet-escape',
    title: 'Sweet Escape',
    category: 'Illustration',
    tagColor: 'pink',
    description: 'A bright and sweet illustration full of delicious things — an ode to the simple joy of desserts, kawaii aesthetics, and summer afternoons.',
    note: 'Drew this while eating too many strawberry mochi.',
    gradient: 'linear-gradient(135deg, #4a1a2a 0%, #6a2a3a 50%, #8a3a4a 100%)',
    accentColor: '#F0C4AA',
    emoji: '🍓',
  },
  {
    id: 'studio-corner',
    title: 'Studio Corner',
    category: 'Personal Work',
    tagColor: 'lavender',
    description: 'A glimpse of my workspace where the magic happens. Warm light, scattered reference books, a half-finished cup of tea.',
    note: 'Some commissions never feel like work.',
    gradient: 'linear-gradient(135deg, #2a2a1a 0%, #3a3a2a 50%, #4a4a3a 100%)',
    accentColor: '#F0C4AA',
    emoji: '🕯️',
  },
]

export const portfolioItems = [
  {
    id: 'azure-empress',
    title: 'Azure Empress',
    category: 'Illustration',
    tagColor: 'pink',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    emoji: '🌙',
    size: 'large',
  },
  {
    id: 'eclipse-of-eternity',
    title: 'Eclipse of Eternity',
    category: 'VTuber',
    tagColor: 'lavender',
    gradient: 'linear-gradient(135deg, #2d1b33 0%, #1a0a2e 100%)',
    emoji: '✦',
    size: 'medium',
  },
  {
    id: 'forgotten-paths',
    title: 'Forgotten Paths',
    category: 'Background',
    tagColor: 'cyan',
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #3a4a5a 100%)',
    emoji: '🏯',
    size: 'medium',
  },
  {
    id: 'sweet-escape',
    title: 'Sweet Escape',
    category: 'Illustration',
    tagColor: 'pink',
    gradient: 'linear-gradient(135deg, #4a1a2a 0%, #8a3a4a 100%)',
    emoji: '🍓',
    size: 'large',
  },
  {
    id: 'midnight-bloom',
    title: 'Midnight Bloom',
    category: 'Personal',
    tagColor: 'lavender',
    gradient: 'linear-gradient(135deg, #1a1a3a 0%, #2a1a4a 100%)',
    emoji: '🌸',
    size: 'small',
  },
  {
    id: 'lantern-festival',
    title: 'Lantern Festival',
    category: 'Illustration',
    tagColor: 'cyan',
    gradient: 'linear-gradient(135deg, #3a1a0a 0%, #6a3a1a 100%)',
    emoji: '🏮',
    size: 'small',
  },
  {
    id: 'stellar-wanderer',
    title: 'Stellar Wanderer',
    category: 'VTuber',
    tagColor: 'pink',
    gradient: 'linear-gradient(135deg, #0a1a3a 0%, #1a0a3a 100%)',
    emoji: '⭐',
    size: 'medium',
  },
  {
    id: 'studio-corner',
    title: 'Studio Corner',
    category: 'Personal',
    tagColor: 'lavender',
    gradient: 'linear-gradient(135deg, #2a2a1a 0%, #4a4a3a 100%)',
    emoji: '🕯️',
    size: 'large',
  },
]

export const projects = [
  {
    id: 'eclipse-of-eternity',
    title: 'Eclipse of Eternity',
    category: 'VTuber Key Visual',
    tagColor: 'lavender',
    year: '2025',
    description: 'A complete key visual project for a VTuber debut. From initial concept sketches through to final polish, this piece needed to capture the character\'s dual nature — gentle by day, powerful by night.',
    brief: 'Create a key visual that communicates "someone who walks between worlds." Dark fantasy with sakura elements.',
    process: [
      'Mood boarding and color palette exploration',
      'Rough character pose sketches (12 variations)',
      'Refined linework with atmospheric background blocking',
      'Color and lighting pass — multiple iterations',
      'Final detail pass and texture work',
    ],
    tools: ['Clip Studio Paint', 'Photoshop', 'PureRef'],
    gradient: 'linear-gradient(135deg, #2d1b33 0%, #1a0a2e 50%, #3d0a0a 100%)',
    emoji: '✦',
    accentColor: '#E8A4B0',
  },
  {
    id: 'forgotten-paths',
    title: 'Forgotten Paths',
    category: 'Background Illustration',
    tagColor: 'cyan',
    year: '2025',
    description: 'Environment background work for an indie visual novel set in a mythical ancient Japan-inspired world. The client needed backgrounds that felt atmospheric and timeless without being static.',
    brief: 'Soft, misty backgrounds with architectural depth. Should feel like somewhere real that no longer exists.',
    process: [
      'Reference gathering — traditional Japanese architecture and atmospheric photography',
      'Perspective and composition planning',
      'Background layer construction',
      'Atmospheric fog and lighting integration',
      'Color grading for mood consistency across the set',
    ],
    tools: ['Clip Studio Paint', 'PureRef', 'Procreate'],
    gradient: 'linear-gradient(135deg, #1a2a3a 0%, #2a3a4a 50%, #3a4a5a 100%)',
    emoji: '🏯',
    accentColor: '#C4B8D4',
  },
  {
    id: 'azure-empress',
    title: 'Azure Empress',
    category: 'Personal Illustration',
    tagColor: 'pink',
    year: '2024',
    description: 'A personal project that started as a lighting study and turned into one of my most detailed character illustrations. Three rounds of rework to find the exact quality of light I wanted.',
    brief: 'Personal challenge: paint "moonlit power" without making it look like every other fantasy illustration.',
    process: [
      'Gesture and silhouette exploration',
      'Fabric study reference sessions',
      'First lighting attempt — scrapped after Round 1',
      'Second approach with stronger rim light — closer',
      'Final version with refined color temperature and detail work',
    ],
    tools: ['Clip Studio Paint', 'Photoshop', 'Blender (lighting ref)'],
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    emoji: '🌙',
    accentColor: '#A8D4D8',
  },
]

export const studioNotes = [
  {
    id: 'about-color',
    date: 'Jul 28',
    title: 'About Color',
    snippet: 'Lately I\'ve been obsessed with soft lighting and vibrant colors. There\'s something about the way golden hour falls on fabric that I keep trying to recreate...',
    emoji: '🎨',
    tag: 'Process',
    tagColor: 'pink',
  },
  {
    id: 'new-brushes',
    date: 'Jul 24',
    title: 'New Brushes',
    snippet: 'Finally found some brushes that feel just right. The texture on these is unlike anything I\'ve used before — it reads almost like watercolor but works digitally.',
    emoji: '🖌️',
    tag: 'Tools',
    tagColor: 'cyan',
  },
  {
    id: 'wip-sneak-peek',
    date: 'Jul 20',
    title: 'WIP Sneak Peek',
    snippet: 'Working on something exciting... ✨ Can\'t say much yet but the palette is soft pinks and dusty lavenders and I am fully obsessed.',
    emoji: '✨',
    tag: 'WIP',
    tagColor: 'lavender',
  },
  {
    id: 'inspiration',
    date: 'Jul 16',
    title: 'Inspiration',
    snippet: 'Watched a random scene from a movie and it completely changed how I think about background depth. The way they used atmospheric perspective...',
    emoji: '🎬',
    tag: 'Inspiration',
    tagColor: 'pink',
  },
  {
    id: 'on-rest',
    date: 'Jul 10',
    title: 'On Rest',
    snippet: 'Took a few days off from drawing and came back with three new ideas. The brain needs space to breathe. Creativity is not a tap you can leave running forever.',
    emoji: '🌿',
    tag: 'Thoughts',
    tagColor: 'cyan',
  },
  {
    id: 'reference-hunt',
    date: 'Jul 04',
    title: 'Reference Hunt',
    snippet: 'Spent three hours in a rabbit hole of traditional Japanese textile patterns. My PureRef board now looks like a museum archive. Worth it.',
    emoji: '📚',
    tag: 'Research',
    tagColor: 'lavender',
  },
]

export const currentlyItems = [
  { label: 'drawing', dot: 'pink' },
  { label: 'eating sweets', dot: 'peach' },
  { label: 'exploring stories', dot: 'lavender' },
  { label: 'daydreaming', dot: 'cyan' },
]
